---
driver:
  name: vagrant
  network:
  - ['forwarded_port', {guest: 15672, host: 15672, auto_correct: true}] # rabbitmq mgt console

provisioner:
  name: ansible_playbook
  # roles_path: ../sensu-client/
  require_chef_for_busser: false
  require_ruby_for_busser: true
  hosts: test-kitchen
  ansible_verbose: true
  ansible_verbosity: 1
  ansible_diff: true
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  requirements_path: test/requirements.yml
  recursive_additional_copy_path:
    - test/include

verifier:
  ruby_bindir: '/usr/bin'

platforms:
- name: ubuntu-14.04
# - name: ubuntu-16.04
- name: centos-6.7
# - name: centos-7.2

suites:
- name: default
