---
- include_vars: "{{ ansible_os_family}}.yml"

- include: "{{ ansible_os_family }}/install.yml"

- include: config.yml
  when: not sensu_install_only

- include: plugins.yml
  when: sensu_gems | length > 0 or sensu_plugins | length > 0

- include: services.yml
  when: not sensu_install_only
